### ISSUE TITLE
Some problems within the PKGBUILD

### ISSUE THREAD

**Issue by fabiscafe** [MultiMC/multimc-pkgbuild#2]
## pkgver
* While package version is pkgver=1.6 the final version is 0.6.14-2998. The PKGBUILD should reflect the changes of the build. This currently is highly confusing.
## deps
* Why is there no `java-runtime` dependency if it's asked for later on?
* Instead of `libgl`, it should be `opengl-driver`, otherwise nvidia proprietary users are not covered
## provides
* `multimc5-git` <- why does it provide this? It is the stable version or a git?
## url
* The multimc page is reachable via https , you should use https here, too

-------
I don't want to get involved in all of this around the AUR support. But let me please say one thing - It will hurt your community the most if you fight over a guideline and do bad packaging as result. With all the respect I can bring up - Please provide a clean, simple and sane PKGBUILD and if that's not possible, please - please let your community to that job without fighting them. The only thing they want is to play games.

**Comment by ImperatorStorm** [comment]
> While package version is pkgver=1.6 the final version is 0.6.14-2998

Reflects version of the `.deb` wrapper, not multimc itself.

**Comment by fabiscafe** [comment]
> Reflects version of the .deb wrapper, not multimc itself.

Maybe a better naming for the package itself would be appropriate in that case.

**Comment by huantianad** [comment]
The PKGBUILD should *not* be providing `multimc5` and `multimc5-git`. Take a look at how all other multimc packages are notated, `multimc` is the name of the base package, which all other versions (official or non-official) should provide.

**Comment by peterix** [comment]
The naming is exactly what it should be.

**Comment by peterix** [comment]
The version is exactly as it should be too.

**Comment by peterix** [comment]
And don't drag 'community' into this. MultiMC is available from multimc.org. Not other sources.

I consider all other packages and distribute channels as illegitimate and unsafe, some outright hostile.

**Comment by peterix** [comment]
The `opengl-driver` point seems fair. Will look into that.

**Comment by huantianad** [comment]
> And don't drag 'community' into this. MultiMC is available from multimc.org. Not other sources.
> 
> 
> 
> I consider all other packages and distribute channels as illegitimate and unsafe, some outright hostile.

In what ways are we bringing this so called 'community' into this?? We are pointing out the mistakes in the PKGBUILD, according to Arch guidelines. We're not promoting any community. The PKGBUILD missing build dependencies or using `provides` incorrectly has nothing to do with 'community'.

**Comment by fabiscafe** [comment]
@peterix Please calm down. The only hostile behavior here is your commenting.
We, the Arch-MultiMC-community, are trying the improve the situation for your PKGBUILD. We, the community, are able to write and use own PKGBUILDs or just avoid MultiMC but we, the community, instead open this report and are trying to improve things for your way.
So please calm down, get your emotions out of the way, stay professional and let's fix these bugs.
