### ISSUE TITLE
What's wrong with multimc-git, multimc-bin, multimc5, ...?

### ISSUE THREAD

**Issue by schmensch** [MultiMC/multimc-pkgbuild#3]
They're all alright and get the job done. MSA Secrets can easily be added. This is just plain worse because no automatic updates.

**Comment by he3als** [comment]
If it is an issue, then why not just make another AUR package? This just makes it more complicated for most people...

**Comment by ImperatorStorm** [comment]
> They're all alright and get the job done. MSA Secrets can easily be added. This is just plain worse because no automatic updates.

they use MultiMC branding without permission, steal API keys from binaries, break multimc's updater, etc.

And this package _does_ have automatic updates. The ones on the AUR don't.

**Comment by Darksilver78** [comment]
> If it is an issue, then why not just make another AUR package? This just makes it more complicated for most people...

> And this package _does_ have automatic updates. The ones on the AUR don't.

Just to clarify, because I was similarly concerned, the package will update alongside all other non-official packages, I.E. with `yay`. Functionally, it's no different than the AUR package. I assume the update button also works as expected. Basically you can update either way, whichever fits your workflow best.

On topic, I believe a note should be added to the site below the download links with a warning and shortlist of installation sources without permissions. Had I not had my MultiMC give the no permissions error and checked AUR I would've been completely unaware of everything going on, and continued with the AUR sources.

**Comment by schmensch** [comment]
This package has automatic updates becaues it breaks AUR Guidelines. You shouldn't just package an installer script, thats really bad practice because it makes MMC very hard to uninstall.

You could also just package a script that automatically builds the latest multimc. That's exactly why multimc-git, multimc5, ... are better.

They don't have MSA support though, but this could be changed easily by adding a UI for changing MSA keys even after compile.

**Comment by Darksilver78** [comment]
I'm not associated with the MultiMC team, but as far as I can tell, this package does everything you're describing in your first two points

It's simple to uninstall, and the script literally builds from the latest MultiMC. Just look at the PKGBUILD and you'll see they just use the debian build to quickly rebuild to arch.

![image](https://user-images.githubusercontent.com/33502716/146679512-66d3b6ff-b01a-405c-8a94-70c14acf99ec.png)

**Comment by ImperatorStorm** [comment]
> You shouldn't just package an installer script, thats really bad practice because it makes MMC very hard to uninstall.

> `steam`

**Comment by schmensch** [comment]
@Darksilver78 look close: All it does is adding a script to download and install MultiMC to /opt/. If you uninstall, it just removes the script and .desktop file, but all the binaries for the installation are still in `~/.local/share/multimc`.

@ImperatorStorm Steam can't be packaged because of licensing restrictions. These do not apply here as MMC is licensed under Apache, which allows redistributing.

**Comment by ImperatorStorm** [comment]
> Steam can't be packaged because of licensing restrictions. These do not apply here as MMC is licensed under Apache, which allows redistributing.

**Launcher** is licensed under the Apache 2.0. **MultiMC** is ARR, as far as I'm aware.

**Comment by peterix** [comment]
Everything, they are junk.

**Comment by schmensch** [comment]
What argument is "everything" you really don't like cooperating, do you?
