### ISSUE TITLE
Removing and reinstalling

### ISSUE THREAD

**Issue by FieryMewtwo** [MultiMC/multimc-pkgbuild#4]
Okay:

So, I installed MultiMC the other day (~1 week ago) and have loved it. One issue though: now my installation is completely busted. It was already busted a few days ago, so I searched the filesystem and deleted anything that wasn't in the repo clone I had made. I tried reinstalling using `makepkg -f` and it crashes on startup. Can someone help me completely purge this so I can play MC again? Thanks!

**Comment by MattSturgeon** [comment]
Unfortunately the package only installs a setup script, so uninstalling the package only removes that setup script, not the actual multimc installation.

The setup script installs multimc into `XDG_DATA_HOME` (usually `~/.local/share`), so to remove multimc you should remove `~/.local/share/multimc`.

**Comment by peterix** [comment]
Terrible advice, you will just delete all your worlds that way. Please do not do this.

**Comment by peterix** [comment]
At the very least, make sure you don't delete the `instances` folder...

**Comment by MattSturgeon** [comment]
> Terrible advice, you will just delete all your worlds that way.

Yep, unfortunately multimc lumps binaries, data, config and cache all into one place, so you do need to be careful when "uninstalling" it.

**Comment by huantianad** [comment]
Who needs the XDG Base Directory Specification anyways?

**Comment by FieryMewtwo** [comment]
Haha my cpu died we're ok
