### ISSUE TITLE
installing multiMC on manjaro Linux not working

### ISSUE THREAD

**Issue by spydragon** [MultiMC/multimc-pkgbuild#6]
I tried the steps for installing multiMC in the read.me (using the git command) everything worked until the last step, "makepkg -si" returns the error:

`curl: (22) The requested URL returned error: 404`
`==> ERROR: Failure while downloading https://files.multimc.org/downloads/multimc_1.6-2.deb`

404 of course meaning "website not found" so I assume it's just a typo in the URL, ether that or I did something wrong.

After looking around the code, it seams the URL in question is on line 24 of the .SRCINFO file. And technically also on line 12 of PKGBUILD.

**Comment by ghost** [comment]
Same issue here, while using both 'git' and 'wget'. not sure what a workaround for this could be but im going to try to find one.

**Comment by ghost** [comment]
You can also just download the binary tarball from the downloads page, that should work out of the box.

**Comment by spydragon** [comment]
> You can also just download the binary tarball from the downloads page, that should work out of the box.

The problem is I’m New to Linux (only around a month) so I have no idea how to use a binary tarball.

**Comment by peterix** [comment]
This should be fixed now.

**Comment by spydragon** [comment]
thank you @peterix
