### ISSUE TITLE
Error getting mod IDs

### ISSUE THREAD

**Issue by poti0n** [MultiMC/multimc-pkgbuild#7]
Unable to resolve mod IDs:
Some mod ID resolving tasks failed.

Can you add documentation on how to do it manually?

**Comment by Recapi** [comment]
Same , looks like the multimc try to download the mods from cursemeta , and recive 502 status code 


![image](https://user-images.githubusercontent.com/507161/169669573-f7ede3ad-ac6c-4a46-86d9-4af895781219.png)


when u try the curse url in browser 

![image](https://user-images.githubusercontent.com/507161/169669652-f46cd464-788e-4a52-b93c-d0dfd1f3a32c.png)

**Comment by peterix** [comment]
This is not the place for reporting issues with the actual software, only the PKGBUILD.

**Comment by peterix** [comment]
See either Discord or the main repo for the actual software.
